### ISSUE TITLE
Twitterで議論中のAndroid4.1.2×three.jsの問題について

### ISSUE THREAD

**Issue by tonkotsuboy** [tonkotsuboy/testCodes#1]
元スレッド
https://twitter.com/tonkotsuboy_com/status/704846328279363585

 takahiro(John Smith) ‏@superhoge  21 時間21 時間前
@tonkotsuboy_com @gyoh_k 修正しました。件のAndroid4.1.2や他の端末で問題が直っているか確認してもらえますか。直っていたら、元々動いていたiOSでも引き続き正しく動いているか念のため見てもらえますかhttp://takahirox.github.io/test/examples/#webgl_animation_cloth

 鹿野壮（Takeshi Kano） ‏@tonkotsuboy_com  21 時間21 時間前
@superhoge @gyoh_k 拝見しました。getShaderPrecisionFormatメソッドのエラーは消えました！ただ、http://takahirox.github.io/test/examples/webgl_animation_cloth.html 　のデモ（元々がそうですが）requestAnimationFrame()メソッドを使っているので、ここでエラーが出ますね。 
requestAnimationFrame()メソッドがAndroid4.1では非対応な為です。http://caniuse.com/#feat=requestanimationframe

デモを再生することに関して言えば、Android4.3以下のみsetInterval()等で代用すれば大丈夫そうですね。

![screenshot_2016-03-03-16-02-24](https://cloud.githubusercontent.com/assets/10419447/13518124/fc241728-e20d-11e5-8995-475447ca2166.png)

 takahiro(John Smith) ‏@superhoge
@tonkotsuboy_com @gyoh_k 確認ありがとうございます。requestAnimationFrame()の問題はまた別問題ですね。直すならばrequestAnimationFrame()非対応のデバイスでも動くようにexamplesを修正するというissueを投げて議論する必要があるでしょう。
ところで、そちらでrequestAnimationFrame()の部分を修正してデモを再生することは可能でしょうか？今回の修正方法だと(WebGLRendererの引数でprecisionを指定しない限り)precisionがhighpに設定されて、それがモバイルデバイスだと非対応の可能性があるので、修正の仕方を少し変えないといけないかもしれないと 気にしていて、とりあえず今対象としている4.1.2の端末ではどうなるか知りたいのです。まぁmediumpになるようにした方がいいと思っていまして、mrdoobとどう直すか少し話をしようとは思っています。

 鹿野壮（Takeshi Kano） ‏@tonkotsuboy_com
@superhoge @gyoh_k そうですね。requestAnimationFrame()は別問題ですね。
試しにこちらでrequestAnimationFrame()を使って実装してみました。
http://tonkotsuboy.github.io/testCodes/160303_android4_webgl_fix/

バグが起こっていたうちの一端末Android4.4(元はAndroid4.0.*)では表示されるようになりました。

![ccnes1zusaiix7o](https://cloud.githubusercontent.com/assets/10419447/13518137/26445d1a-e20e-11e5-80f7-07e7ae13c11e.jpg)

しかし、 Android 4.1.2の方では "THREE.WebGLShader: Shader couldn't comile" というエラーにより表示できません。 

![screenshot_2016-03-03-17-34-19](https://cloud.githubusercontent.com/assets/10419447/13518146/31d41fb2-e20e-11e5-90b1-7f60e54322c9.png)

 takahiro(John Smith) ‏@superhoge  20 時間20 時間前
@tonkotsuboy_com @gyoh_k おそらくprecisionの問題ですね。WebGLRendererをnewしてるところの引数にprecision:'mediump'を追加して、4.1.2でもう一度試してもらうことってできますか？

 鹿野壮（Takeshi Kano） ‏@tonkotsuboy_com
@superhoge @gyoh_k  うーむ、変わらないですねえ。。
http://tonkotsuboy.github.io/testCodes/160303_android4_webgl_fix/

 takahiro(John Smith) ‏@superhoge  19 時間19 時間前
@tonkotsuboy_com @gyoh_k コンパイルエラーのログってコンソールに出ませんでしたか？もしprecisionの問題ではないとすると、また別の問題にぶつかっている可能性があります。

鹿野壮（Takeshi Kano）
@superhoge @gyoh_k 
コンパイルエラーは以前のものと全く同じです。

takahiro(John Smith)
‏@superhoge
@tonkotsuboy_com @gyoh_k 3つお願いがあります。件のAndroid4.1.2端末で 
1. 先のprecisionを指定したサンプル上でrenderer.getPrecision()の結果が'mediump'になっていることを確認してほしい
2. このページを開いて https://www.browserleaks.com/webgl  その結果を見せてほしい 
3. ここ http://takahirox.github.io/test/examples/index.html で 同じようにcompile errorになるか確認してほしい。(できればgeometry/cubeなどの簡単なサンプルで)

おそらくですがprecisionの問題ではないような気がしていて、また新たな別の問題にぶつかっている気がします。その場合、shaderプログラムのコードをdumpして怪しいところを探すなどの作業が必要になってくると思います。

元々のgetShaderPrecisionFormatがないことによるエラーは今回の修正で直っているので、PRを送ることで当初の問題は一旦クローズして、必要ならAndroid4.1.2でshaderのコンパイルエラーが起きたという新たなissueを投げるのがいいのではと思っています。

**Comment by ics-kano** [comment]
@takahirox
1. 先のprecisionを指定したサンプル上でrenderer.getPrecision()の結果が'mediump'になっていることを確認してほしい

について、こちらについて`renderer.getPrecision()`のアラートを出すようにしました。Android 4.1.2で閲覧した時も`mediump`となっているようです。

http://tonkotsuboy.github.io/testCodes/160303_android4_webgl_fix/

![screenshot_2016-03-04-13-26-22](https://cloud.githubusercontent.com/assets/7123759/13518225/039ba862-e20f-11e5-8999-f389ccb4e712.png)

**Comment by tonkotsuboy** [comment]
@takahirox
1. 先のprecisionを指定したサンプル上でrenderer.getPrecision()の結果が'mediump'になっていることを確認してほしい

について、こちらについてrenderer.getPrecision()のアラートを出すようにしました。Android 4.1.2で閲覧した時もmediumpとなっているようです。

http://tonkotsuboy.github.io/testCodes/160303_android4_webgl_fix/

![screenshot_2016-03-04-13-26-22](https://cloud.githubusercontent.com/assets/10419447/13518261/38107294-e20f-11e5-8af1-a26ed0171b63.png)

**Comment by tonkotsuboy** [comment]
@takahirox
2. このページを開いて https://www.browserleaks.com/webgl その結果を見せてほしい について
件のAndroid 4.1.2での結果を送ります。

![screenshot_2016-03-04-13-45-46](https://cloud.githubusercontent.com/assets/10419447/13518300/8f6fe222-e20f-11e5-8ec2-9229444f3a0a.png)

![screenshot_2016-03-04-13-45-57](https://cloud.githubusercontent.com/assets/10419447/13518305/97049e9c-e20f-11e5-8c67-6dab0a41b12e.png)

**Comment by ics-kano** [comment]
@takahirox 
3. ここ http://takahirox.github.io/test/examples/index.html で 同じようにcompile errorになるか確認してほしい。(できればgeometry/cubeなどの簡単なサンプルで) について

同じようにcompile errorとなります。

http://takahirox.github.io/test/examples/index.html#webgl_geometries
![screenshot_2016-03-04-13-51-53](https://cloud.githubusercontent.com/assets/7123759/13518421/df84b192-e210-11e5-8211-0709ddf26af1.png)

http://takahirox.github.io/test/examples/index.html#webgl_geometry_cube
![screenshot_2016-03-04-13-50-42](https://cloud.githubusercontent.com/assets/7123759/13518415/c5d5946e-e210-11e5-9b7e-b464edb50fb1.png)

http://takahirox.github.io/test/examples/index.html#webgl_lines_colors
![screenshot_2016-03-04-13-57-12](https://cloud.githubusercontent.com/assets/7123759/13518435/0ee9166c-e211-11e5-8567-6da3b8890c73.png)

**Comment by tonkotsuboy** [comment]
@takahirox 
3. ここ http://takahirox.github.io/test/examples/index.html で 同じようにcompile errorになるか確認してほしい。(できればgeometry/cubeなどの簡単なサンプルで) について

同じようにcompile errorとなります。

http://takahirox.github.io/test/examples/index.html#webgl_geometries
![screenshot_2016-03-04-13-51-53](https://cloud.githubusercontent.com/assets/7123759/13518421/df84b192-e210-11e5-8211-0709ddf26af1.png)

http://takahirox.github.io/test/examples/index.html#webgl_geometry_cube
![screenshot_2016-03-04-13-50-42](https://cloud.githubusercontent.com/assets/7123759/13518415/c5d5946e-e210-11e5-9b7e-b464edb50fb1.png)

http://takahirox.github.io/test/examples/index.html#webgl_lines_colors
![screenshot_2016-03-04-13-57-12](https://cloud.githubusercontent.com/assets/7123759/13518435/0ee9166c-e211-11e5-8567-6da3b8890c73.png)

**Comment by takahirox** [comment]
対応ありがとうございました。

WebGLパラメータから何かわかるかもと期待していたのですが、
コンパイルエラーの原因はやはりshaderプログラムをダンプして眺めたりしないとよくわからないですね。

本来はコンソールにコンパイルエラーログが出力されるはずなのですが、
それが表示されていない理由もよくわかりません。

getShaderPrecisionFormatの件はPRを送ってcloseしようと思います。
precision指定なしの場合mediumpにすべきかなと思ったのですが、
色々面倒そうなので今のままPRを投げる予定です。

コンパイルエラーの件は必要ならば新たにThree.js に issueを投げてください。

**Comment by takahirox** [comment]
PRがmergeされました。

https://github.com/mrdoob/three.js/pull/8290

r75からgetShaderPrecisionFormatのエラーは消えるはずです。

**Comment by takahirox** [comment]
ちなみに Android 4.1.2 でこのサンプルは表示できますか？

http://takahirox.github.io/test/examples/index.html#webgl_buffergeometry_rawshader

これはRawShaderMaterialを使ってcustom shaderを実装しているので、
通常のMaterialを使うよりもかなりシンプルなshaderプログラムになっています。

コンパイルエラーになったとしても、これなら調査がしやすいでしょう。

**Comment by tonkotsuboy** [comment]
@takahirox 

> 本来はコンソールにコンパイルエラーログが出力されるはずなのですが、

下記画像の赤字部分が、コンソールでのコンパイルエラーであるという認識なのですが、この他に何か表示されるということでしょうか？

![screenshot_2016-03-04-13-57-12](https://cloud.githubusercontent.com/assets/7123759/13518435/0ee9166c-e211-11e5-8567-6da3b8890c73.png)

**Comment by tonkotsuboy** [comment]
> ちなみに Android 4.1.2 でこのサンプルは表示できますか？
> http://takahirox.github.io/test/examples/index.html#webgl_buffergeometry_rawshader

詳しく調査する時間は持てないのですが、結果を共有します。
下記のようにエラーが発生します。

```
Object #<Performance> has no method 'now'
```

![screenshot_2016-03-05-22-07-35](https://cloud.githubusercontent.com/assets/10419447/13547658/ee9d880c-e31e-11e5-85ae-5d0792fb8db3.png)

**Comment by takahirox** [comment]
この辺を見ると赤字の部分の後に付随する情報が出てもおかしくないのですが。

https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLShader.js#L30-L34
https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLProgram.js#L494-L499

performance.nowのpolyfillを追加しました。
もう一度サンプルの表示を試してみてもらえますか？

http://takahirox.github.io/test/examples/index.html#webgl_buffergeometry_rawshader

**Comment by tonkotsuboy** [comment]
@takahirox 
サンプルをAndroid 4.1.2で見たところ、表示されました。

![screenshot_2016-03-07-11-35-19](https://cloud.githubusercontent.com/assets/10419447/13560663/34d9940e-e465-11e5-90c8-9af11e217122.png)

**Comment by takahirox** [comment]
確認ありがとうございます。

このサンプルが表示されるとなると、標準のMaterial群で使われている
shaderプログラムの中にAndroid4.1.2のWebGLで
解釈できない命令かなにかが含まれているのではと思われます。
このサンプルでもmediumpが使われているので、precision以外の問題と思われます。

コンパイルエラーログが表示されない以上、
自分で具体的な問題箇所を見つけてPRを送らないと修正されないのではという気がします。

ちなみに私のPC上ではコンパイラエラーログがコンソールに表示されました。
上記rawshaderサンプルで適当にshaderをコンパイルできないように書き換えて
PC上で見てみると、本来どのようにコンパイラエラーログが表示されるかが確認できると思います。

**Comment by tonkotsuboy** [comment]
@takahirox 
ありがとうございます。

Shader周りはちょっと自信が無いので、調査自体はここで終了しようと思います。
